services:
  - type: web
    name: lapanginaja-api
    runtime: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    plan: free
    envVars:
      - key: APP_NAME
        value: LapanginAja
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: MAIL_MAILER
        value: brevo
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: LapanginAja
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: MIDTRANS_IS_PRODUCTION
        value: "false"
      - key: MIDTRANS_SNAP_URL
        value: https://app.sandbox.midtrans.com/snap/snap.js
      - key: MIDTRANS_IS_SANITIZED
        value: "true"
      - key: MIDTRANS_IS_3DS
        value: "true"
